### PR TITLE
Fix a broken SRC_URI in x11-misc/ly

### PR DESCRIPTION
**Pull request by flexagoon**

### CODE REVIEW

**Comment by liangyongxiang** [comment]
The master branch corresponds to the live package in gentoo, if you need it, you can submit ly-9999.ebuild

**Comment by liangyongxiang** [comment]
@Chi-Tan-Da-Eru 你漏了git-r3_fetch了吗？

**Comment by flexagoon** [comment]
> The master branch corresponds to the live package in gentoo, if you need it, you can submit ly-9999.ebuild

ly is no longer updated, so just using "master" would do the same thing as specifying its version

**Comment by liangyongxiang** [comment]
> > The master branch corresponds to the live package in gentoo, if you need it, you can submit ly-9999.ebuild
> 
> ly is no longer updated, so just using "master" would do the same thing as specifying its version

But if it is updated, it may not be able to compile. 
The problem of SRC_URI can be solved like this:
```
SRC_URI="${HOMEPAGE}/archive/refs/tags/v${PV}.tar.gz
```

**Comment by flexagoon** [comment]
Okay, I changed it

**Pull request merged**
