### PR TITLE
add dev-python/Quamash needed by NetEaseMusic potentially to add

### PR DESCRIPTION
**Pull request by WallanceLee**
NetEaseMusic dependency python3's module Quamash

### CODE REVIEW

**Comment by WallanceLee** [comment]
This module is needed by NetEaseMusic.See github.com/cosven/FeelUOwn/requirements.txt

**Comment by biergaizi** [comment]
This is not even the same project, but the Python module looks fine.

**Comment by biergaizi** [comment]
But please don't use uppercase letters, if only the first letter of the package is in uppercase, or people will difficult to find it.

**Comment by WallanceLee** [comment]
Thanks

**Pull request merged**
