### PR TITLE
net-im/tencent-qq: add 3.2.12_p26740, drop 3.2.9_p26909

### PR DESCRIPTION
**Pull request by haowuge**

### CODE REVIEW

**Comment by liangyongxiang** [comment]
```
pkgdev manifest
--2024-08-15 09:53:52--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_amd64.deb
Resolving dldir1.qq.com... 61.152.119.252, 61.152.119.254, 240e:96c:6000:880::b00:53, ...
Connecting to dldir1.qq.com|61.152.119.252|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-15 09:53:53 ERROR 404: Not Found.

--2024-08-15 09:53:53--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_arm64.deb
Resolving dldir1.qq.com... 61.152.119.254, 61.152.119.252, 240e:96c:6000:880::b00:62, ...
Connecting to dldir1.qq.com|61.152.119.254|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-15 09:53:53 ERROR 404: Not Found.

--2024-08-15 09:53:53--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_loongarch64.deb
Resolving dldir1.qq.com... 61.152.119.252, 61.152.119.254, 240e:96c:6000:880::b00:62, ...
Connecting to dldir1.qq.com|61.152.119.252|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-08-15 09:53:53 ERROR 404: Not Found.

 * failed fetching file: linuxqq_3.2.12-26909_amd64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_amd64.deb
 * failed fetching file: linuxqq_3.2.12-26909_arm64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_arm64.deb
 * failed fetching file: linuxqq_3.2.12-26909_loongarch64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_loongarch64.deb
 * failed fetching files for package net-im/tencent-qq::gentoo-zh
pkgdev manifest: error: failed fetching required distfiles
```

**Comment by haowuge** [comment]
> ```
> pkgdev manifest
> --2024-08-15 09:53:52--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_amd64.deb
> Resolving dldir1.qq.com... 61.152.119.252, 61.152.119.254, 240e:96c:6000:880::b00:53, ...
> Connecting to dldir1.qq.com|61.152.119.252|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2024-08-15 09:53:53 ERROR 404: Not Found.
> 
> --2024-08-15 09:53:53--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_arm64.deb
> Resolving dldir1.qq.com... 61.152.119.254, 61.152.119.252, 240e:96c:6000:880::b00:62, ...
> Connecting to dldir1.qq.com|61.152.119.254|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2024-08-15 09:53:53 ERROR 404: Not Found.
> 
> --2024-08-15 09:53:53--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_loongarch64.deb
> Resolving dldir1.qq.com... 61.152.119.252, 61.152.119.254, 240e:96c:6000:880::b00:62, ...
> Connecting to dldir1.qq.com|61.152.119.252|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2024-08-15 09:53:53 ERROR 404: Not Found.
> 
>  * failed fetching file: linuxqq_3.2.12-26909_amd64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_amd64.deb
>  * failed fetching file: linuxqq_3.2.12-26909_arm64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_arm64.deb
>  * failed fetching file: linuxqq_3.2.12-26909_loongarch64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_loongarch64.deb
>  * failed fetching files for package net-im/tencent-qq::gentoo-zh
> pkgdev manifest: error: failed fetching required distfiles
> ```

对不起，我晚上回去改
（从~/gentoo-zh拷到/var/db/repos测试安装的时候，发现有错，直接改了，然后忘记覆盖回来~里的库了）

**Comment by liangyongxiang** [comment]
> > ```
> > pkgdev manifest
> > --2024-08-15 09:53:52--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_amd64.deb
> > Resolving dldir1.qq.com... 61.152.119.252, 61.152.119.254, 240e:96c:6000:880::b00:53, ...
> > Connecting to dldir1.qq.com|61.152.119.252|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2024-08-15 09:53:53 ERROR 404: Not Found.
> > 
> > --2024-08-15 09:53:53--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_arm64.deb
> > Resolving dldir1.qq.com... 61.152.119.254, 61.152.119.252, 240e:96c:6000:880::b00:62, ...
> > Connecting to dldir1.qq.com|61.152.119.254|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2024-08-15 09:53:53 ERROR 404: Not Found.
> > 
> > --2024-08-15 09:53:53--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_loongarch64.deb
> > Resolving dldir1.qq.com... 61.152.119.252, 61.152.119.254, 240e:96c:6000:880::b00:62, ...
> > Connecting to dldir1.qq.com|61.152.119.252|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2024-08-15 09:53:53 ERROR 404: Not Found.
> > 
> >  * failed fetching file: linuxqq_3.2.12-26909_amd64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_amd64.deb
> >  * failed fetching file: linuxqq_3.2.12-26909_arm64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_arm64.deb
> >  * failed fetching file: linuxqq_3.2.12-26909_loongarch64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_loongarch64.deb
> >  * failed fetching files for package net-im/tencent-qq::gentoo-zh
> > pkgdev manifest: error: failed fetching required distfiles
> > ```
> 
> 对不起，我晚上回去改 （从~/gentoo-zh拷到/var/db/repos测试安装的时候，发现有错，直接改了，然后忘记覆盖回来~里的库了）

如果你想测试，可以在~/gentoo-zh 目录下运行 
```
ebuild /path/tencent-qq.xxx.ebuild clean install 
```

它会安装 PORTAGE_TMP/net-im/tencent-qq-xxx/image/目录下，然后你可以使用绝对路径进行简单的运行测试。

**Comment by liangyongxiang** [comment]
> > ```
> > pkgdev manifest
> > --2024-08-15 09:53:52--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_amd64.deb
> > Resolving dldir1.qq.com... 61.152.119.252, 61.152.119.254, 240e:96c:6000:880::b00:53, ...
> > Connecting to dldir1.qq.com|61.152.119.252|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2024-08-15 09:53:53 ERROR 404: Not Found.
> > 
> > --2024-08-15 09:53:53--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_arm64.deb
> > Resolving dldir1.qq.com... 61.152.119.254, 61.152.119.252, 240e:96c:6000:880::b00:62, ...
> > Connecting to dldir1.qq.com|61.152.119.254|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2024-08-15 09:53:53 ERROR 404: Not Found.
> > 
> > --2024-08-15 09:53:53--  https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_loongarch64.deb
> > Resolving dldir1.qq.com... 61.152.119.252, 61.152.119.254, 240e:96c:6000:880::b00:62, ...
> > Connecting to dldir1.qq.com|61.152.119.252|:443... connected.
> > HTTP request sent, awaiting response... 404 Not Found
> > 2024-08-15 09:53:53 ERROR 404: Not Found.
> > 
> >  * failed fetching file: linuxqq_3.2.12-26909_amd64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_amd64.deb
> >  * failed fetching file: linuxqq_3.2.12-26909_arm64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_arm64.deb
> >  * failed fetching file: linuxqq_3.2.12-26909_loongarch64.deb, uri: https://dldir1.qq.com/qqfile/qq/QQNT/769073aa/linuxqq_3.2.12-26909_loongarch64.deb
> >  * failed fetching files for package net-im/tencent-qq::gentoo-zh
> > pkgdev manifest: error: failed fetching required distfiles
> > ```
> 
> 对不起，我晚上回去改 （从~/gentoo-zh拷到/var/db/repos测试安装的时候，发现有错，直接改了，然后忘记覆盖回来~里的库了）

https://github.com/microcai/gentoo-zh/pull/5084

**Pull request merged**
