### PR TITLE
net-im/tencent-qq: add 3.2.7_p240410, drop 3.2.7_p240403 and Add support for loong64

### PR DESCRIPTION
**Pull request by haowuge**
net-im/tencent-qq: add 3.2.7_p240410, drop 3.2.7_p240403 and Add support for loong64

### CODE REVIEW

**Comment by liangyongxiang** [comment]
It and its dependencies lack the loong keyword.
I tested it to work on a 3c5000 (not logged in)

**Comment by haowuge** [comment]
> It and its dependencies lack the loong keyword. I tested it to work on a 3c5000 (not logged in)

Okay, the code has been updated again. Thank you.

**Comment by liangyongxiang** [comment]
It also has two dependencies that need to be keyworded: 
``` 
x11-misc/snapd-xdg-open
media-libs/openslide
```
You can use ekeyword to update ebuild.
```
ekeyword '~loong' /path/x11-misc/snapd-xdg-open/snapd-xdg-open-20170401.ebuild
```

It's best to only modify one ebuild per commit.

**Comment by liangyongxiang** [comment]
我其实是想表达：一个pr里面可以有多个commit，每个commit只修改一个ebuild

**Pull request merged**
