### PR TITLE
net-im/wemeet: add 3.19.1.400 & 3.19.1.401

### PR DESCRIPTION
**Pull request by xen0n**
~~Untested right now~~ I've lightly tested on amd64 only (login, settings, A/V test, conference), please test before merging!

### CODE REVIEW

**Comment by xen0n** [comment]
Hmm, there's a `package.mask` entry here, but apparently not working, because the `::gentoo` x32 profile, if selected, will of course not look up `::gentoo-zh` directories.

**Comment by liangyongxiang** [comment]
> Hmm, there's a `package.mask` entry here, but apparently not working, because the `::gentoo` x32 profile, if selected, will of course not look up `::gentoo-zh` directories.

https://github.com/microcai/gentoo-zh/issues/3139
https://github.com/pkgcore/pkgcheck/issues/402

**Comment by liangyongxiang** [comment]
```
% wemeetapp
/opt/wemeet/bin/wemeetapp: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```

**Comment by liangyongxiang** [comment]
ping

**Comment by xen0n** [comment]
Sorry for the long delay (it fell off my radar and I've been extremely occupied with Real Life:tm: recently to begin with).

Qt is no longer unbundled due to ABI mismatch, so Qt libraries no longer appear on `RDEPEND` and the `pkgcheck` error should be gone. The package should still not work on x32 systems though.

**Comment by xen0n** [comment]
oh well, what can I say ¯\_(ツ)_/¯

**Pull request merged**
