### PR TITLE
net-im/tencent-qq: fix bwrap bind dconf

### LINKED ISSUE #4504: net-im/tencent-qq bwrap `~/.config/dconf` to make gsettings styling work
In the net-im/tencent-qq package, the ~/.config/dconf directory is not correctly mapped by bwrap in start.sh. As a result, user-defined themes configured via gsettings are not applied as expected.

Observable Issues:

* Cursor theme and size revert to Adwaita/24 on all QQ windows.
* File pickers appear in the Adwaita theme.

[Reference AUR comment](https://aur.archlinux.org/packages/linuxqq-nt-bwrap#comment-962302)

I don't know whether other bwrap packages are facing similar problems, which could be open for discussion.

The fix should be like

```diff
--- gentoo-zh/net-im/tencent-qq/files/start.sh	2024-01-06 16:51:00.299369685 +0800
+++ local/net-im/tencent-qq/files/start.sh	2024-04-10 19:06:21.912161246 +0800
@@ -120,6 +120,7 @@
     --ro-bind-try "${FONTCONFIG_HOME}" "${FONTCONFIG_HOME}" \
     --ro-bind-try "${HOME}/.icons" "${HOME}/.icons" \
     --ro-bind-try "${HOME}/.local/share/.icons" "${HOME}/.local/share/.icons" \
+    --ro-bind-try "${HOME}/.config/dconf" "${HOME}/.config/dconf" \
     --ro-bind-try "${XDG_CONFIG_HOME}/gtk-3.0" "${XDG_CONFIG_HOME}/gtk-3.0" \
     --ro-bind /etc/nsswitch.conf /etc/nsswitch.conf \
     --ro-bind-try /run/systemd/userdb/ /run/systemd/userdb/ \
```

### PR DESCRIPTION
**Pull request by seven-mile**
Fix #4504 .

I renamed ebuild to a new revision. It should work, right?

### CODE REVIEW

**Comment by st0nie** [comment]
I think nothing need to be changed

For the file picker:
Set `GTK_USE_PORTAL=1`
For the cursor:
`ln -s /usr/share/icons/breeze_cursors ~/.icons/default`

**Comment by seven-mile** [comment]
@st0nie Great. But seemingly the cursor size still cannot be resolved with the mix of several adhoc solutions. Furthermore, users have to maintain the symbolic linkage if they want to switch to another icon theme.

Is there any reason to keep user gsettings from taking effects in bwrap? It will be fine if everything works out of box.

**Comment by st0nie** [comment]
You 'd better talk to the uptream directly.
If they wanna add dconf, we 'll follow them

https://aur.archlinux.org/cgit/aur.git/tree/start.sh?h=linuxqq-nt-bwrap

**Comment by st0nie** [comment]
Another solution is to use Xwayland.
By this way, qq reads `~/.config/gtk-3.0` which is maintained by `xsettingsd`
Sometimes qq's clipboard loses functionality with pure wayland, so I've been using xwayland.

**Pull request closed without merging**
