### PR TITLE
net-im/wechat-universal-bwrap: add 1.0.0.241, drop 1.0.0.238-r2

### PR DESCRIPTION
**Pull request by haowuge**
fix:https://github.com/microcai/gentoo-zh/issues/4621

### CODE REVIEW

**Comment by haowuge** [comment]
> ## ⚪ `pkgcheck` checks passed but with something can be improved!
> 
>     * pkgcheck 0.10.29
> 
>     * the corresponding _**::gentoo**_ commit: [gentoo-mirror/gentoo@f9f5eb4](https://github.com/gentoo-mirror/gentoo/commit/f9f5eb4a521ec97964e66a2b16d36eca8b377405)
> 
> 
> QA Results:
> 
> ```
> net-im/wechat-universal-bwrap
>   ExcessiveLineLength: version 1.0.0.241: excessive line length (over 120 characters) on lines: 17, 107
> ```
> 
> [🔍 QA Keywords Explanation](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#keywords)

大佬们，超长的字段应该通过 \方式换行？还是忽略？，因为这个107用\换行并不合适的样子，谢谢

**Comment by HougeLangley** [comment]
@Universebenzene 天笨帮忙看看，谢谢

> > ## ⚪ `pkgcheck` checks passed but with something can be improved!
> > ```
> > * pkgcheck 0.10.29
> > 
> > * the corresponding _**::gentoo**_ commit: [gentoo-mirror/gentoo@f9f5eb4](https://github.com/gentoo-mirror/gentoo/commit/f9f5eb4a521ec97964e66a2b16d36eca8b377405)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > QA Results:
> > ```
> > net-im/wechat-universal-bwrap
> >   ExcessiveLineLength: version 1.0.0.241: excessive line length (over 120 characters) on lines: 17, 107
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [🔍 QA Keywords Explanation](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#keywords)
> 
> 大佬们，超长的字段应该通过 \方式换行？还是忽略？，因为这个107用\换行并不合适的样子，谢谢

**Comment by liangyongxiang** [comment]
> > ## ⚪ `pkgcheck` checks passed but with something can be improved!
> > ```
> > * pkgcheck 0.10.29
> > 
> > * the corresponding _**::gentoo**_ commit: [gentoo-mirror/gentoo@f9f5eb4](https://github.com/gentoo-mirror/gentoo/commit/f9f5eb4a521ec97964e66a2b16d36eca8b377405)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > QA Results:
> > ```
> > net-im/wechat-universal-bwrap
> >   ExcessiveLineLength: version 1.0.0.241: excessive line length (over 120 characters) on lines: 17, 107
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [🔍 QA Keywords Explanation](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#keywords)
> 
> 大佬们，超长的字段应该通过 \方式换行？还是忽略？，因为这个107用\换行并不合适的样子，谢谢

一般来说，这些问题是应该在本地跑的。在你修改的ebuild的目录执行 ```pkgcheck scan .```就好

github的代码模板有很多限制的。这就是现代前端。

**Comment by liangyongxiang** [comment]
哦哦。我理解错了， ExcessiveLineLength 的问题要么你修改成更短，要么就忽略警告。

**Comment by HougeLangley** [comment]
目前我先合并，后续再修改喽？各位是否有不同意见～

**Comment by HougeLangley** [comment]
合了，后续再慢慢修～

**Comment by Universebenzene** [comment]
> @Universebenzene 天笨帮忙看看，谢谢
> 
> > > ## ⚪ `pkgcheck` checks passed but with something can be improved!
> > > ```
> > > * pkgcheck 0.10.29
> > > 
> > > * the corresponding _**::gentoo**_ commit: [gentoo-mirror/gentoo@f9f5eb4](https://github.com/gentoo-mirror/gentoo/commit/f9f5eb4a521ec97964e66a2b16d36eca8b377405)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > QA Results:
> > > ```
> > > net-im/wechat-universal-bwrap
> > >   ExcessiveLineLength: version 1.0.0.241: excessive line length (over 120 characters) on lines: 17, 107
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [🔍 QA Keywords Explanation](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#keywords)
> > 
> > 
> > 大佬们，超长的字段应该通过 \方式换行？还是忽略？，因为这个107用\换行并不合适的样子，谢谢

我正好11点到12点期间没空看github，等上线看到@的时候已经被merge了……

我想说的是楼主引用的 #4621 里 [这个评论](https://github.com/microcai/gentoo-zh/issues/4490#issuecomment-2076715323) 提到的修复方法没人搞一下？我不在Gentoo上用微信所以没测试

**Comment by liangyongxiang** [comment]
有人有兴趣可以尝试一下，我在虚拟机里面跑微信。

**Comment by HougeLangley** [comment]
目前我这边龙芯上会出现 bug 启动不了 https://github.com/microcai/gentoo-zh/issues/4631

**Comment by haowuge** [comment]
我现在

> > @Universebenzene 天笨帮忙看看，谢谢
> > > > ## ⚪ `pkgcheck` checks passed but with something can be improved!
> > > > ```
> > > > * pkgcheck 0.10.29
> > > > 
> > > > * the corresponding _**::gentoo**_ commit: [gentoo-mirror/gentoo@f9f5eb4](https://github.com/gentoo-mirror/gentoo/commit/f9f5eb4a521ec97964e66a2b16d36eca8b377405)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > QA Results:
> > > > ```
> > > > net-im/wechat-universal-bwrap
> > > >   ExcessiveLineLength: version 1.0.0.241: excessive line length (over 120 characters) on lines: 17, 107
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > [🔍 QA Keywords Explanation](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#keywords)
> > > 
> > > 
> > > 大佬们，超长的字段应该通过 \方式换行？还是忽略？，因为这个107用\换行并不合适的样子，谢谢
> 
> 我正好11点到12点期间没空看github，等上线看到@的时候已经被merge了……
> 
> 我想说的是楼主引用的 #4621 里 [这个评论](https://github.com/microcai/gentoo-zh/issues/4490#issuecomment-2076715323) 提到的修复方法没人搞一下？我不在Gentoo上用微信所以没测试

马上搞，测试能跑的起来

**Pull request merged**
