### PR TITLE
new package: net-im/telegram-desktop

### PR DESCRIPTION
**Pull request by PeterCxy**
the lastest 0.8.50 dev version, with fcitx/ibus support

Signed-off-by: Peter Cai xqsx43cxy@126.com

### CODE REVIEW

**Comment by biergaizi** [comment]
```
qt-everywhere-opensource-src-$_qtver.tar.xz -> qt.tar.xz
```

Please always contain a version number in the file names, or it'll cause name conflict during upgrading. 

In your case, you don't have to rename the package at all, just use the original name. Because Qt in portage uses the same name, users who already downloaded Qt will not have to download the same file again.

**Comment by PeterCxy** [comment]
@biergaizi fixed.

**Comment by biergaizi** [comment]
```
RDEPEND="
    x11-base/xorg-server[xvfb]
```

I think it is a compile-time dependency, better to move to it `DEPEND` instead of `RDEPEND`?

**Comment by biergaizi** [comment]
```
DEPEND=">=dev-libs/dee-1.2.5:=
    dev-libs/libdbusmenu:=
    dev-libs/libgee:0
    x11-libs/gtk+:3
    ${PYTHON_DEPS}
    $(vala_depend)"
```

This is no `RDEPEND`, you should define a `RDEPEND`, and in your case, just refers to `DEPEND`.

```
RDEPEND="${DEPEND}"
```

`DEPEND` is compile-time dependencies, and `RDEPEND` is runtime dependencies. All `DEPEND` will be remove by `emerge --depclean` since the compilation is complete.

**Comment by PeterCxy** [comment]
@biergaizi done.

**Comment by biergaizi** [comment]
lgtm-anpo-saiketsu

Looks good to me! Thanks for your efforts on this tricky package!

**Pull request merged**
