### PR TITLE
Bump app-editor/zed to version 0.144.4

### LINKED ISSUE #4944: app-editors/zed doesn't compile with virtual/rust-1.78.0
The packages dependency (installed while compiling) now requires rust version 1.79.0. I would consider changing the ebuild to consider this.

### PR DESCRIPTION
**Pull request by smoliicek**
could fix #4944 
if any problems arise, feel free to contact me :)

### CODE REVIEW

**Comment by liuyujielol** [comment]
Could you update the ebuild?

The crates list is not changed, just rename to zed-0.144.4.ebuild & run `pkgdev manifest` in the directory would do.

**Comment by smoliicek** [comment]
this should do it :D

**Comment by liuyujielol** [comment]
Thanks!

**Comment by liangyongxiang** [comment]
> Thanks!

If you think this pr is good enough, please approve it.

**Comment by smoliicek** [comment]
thanks!

**Comment by liuyujielol** [comment]
> 
> If you think this pr is good enough, please approve it.

I did not actually give a review, there is no approve button.

**Comment by liuyujielol** [comment]
> I did not actually give a review, there is no approve button.

要有写入和管理权限，下次直接发评论吧

**Comment by liangyongxiang** [comment]
> > I did not actually give a review, there is no approve button.
> 
> 要有写入和管理权限，下次直接发评论吧

好的。一般有人review之后，我就不怎么看就合并了。

**Pull request merged**
