### PR TITLE
remove net-proxy/trojan; move net-proxy/v2ray-bin to net-proxy/v2ray

### PR DESCRIPTION
**Pull request by YangMame**

### CODE REVIEW

**Comment by wgjak47** [comment]
Something wrong with net-proxy/trojan?

**Comment by microcai** [comment]
trojan 404 ?

**Comment by wgjak47** [comment]
No, It just need updated... https://github.com/trojan-gfw/trojan/releases

**Comment by YangMame** [comment]
> No, It just need updated... https://github.com/trojan-gfw/trojan/releases

https://github.com/gentoo/gentoo/tree/master/net-proxy/trojan 
I've uploaded it to gentoo repo
there is no need for update

**Comment by wgjak47** [comment]
OK

**Pull request merged**
