### PR TITLE
app-i18n/fcitx-anthy: add 5.1.2, drop 5.0.14

### PR DESCRIPTION
**Pull request by liuyujielol**

### CODE REVIEW

**Comment by liuyujielol** [comment]
```
BDEPEND="
+	test? (
+		coverage? ( dev-util/lcov )
+	)
	kde-frameworks/extra-cmake-modules:5
	virtual/pkgconfig
"
```
刚rebase完就合了.....

**Comment by liangyongxiang** [comment]
> ```
> BDEPEND="
> +	test? (
> +		coverage? ( dev-util/lcov )
> +	)
> 	kde-frameworks/extra-cmake-modules:5
> 	virtual/pkgconfig
> "
> ```
> 
> 刚rebase完就合了.....

有什么问题吗

**Comment by liuyujielol** [comment]
忘记加test的BDEPEND了

**Comment by liuyujielol** [comment]
帮忙加一下吧

> ```
> BDEPEND="
> +	test? (
> +		coverage? ( dev-util/lcov )
> +	)
> 	kde-frameworks/extra-cmake-modules:5
> 	virtual/pkgconfig
> "
> ```
>

**Comment by liangyongxiang** [comment]
@liuyujielol 我在外面，你重新pr一下?

**Pull request merged**
