### PR TITLE
x11-plugins/pidgin-lwqq: update to 0.4.1

### PR DESCRIPTION
**Pull request by PeterCxy**
From now on pidgin-lwqq depends on liblwqq instead of including the source code of liblwqq. So I updated pidgin-lwqq and added liblwqq as a dependency of pidgin-lwqq.

### CODE REVIEW

**Comment by biergaizi** [comment]
```
KEYWORDS="~x86 amd64"
```

Typo. Stable or unstable?

**Comment by PeterCxy** [comment]
@biergaizi Untested under x86 but tested under amd64

**Comment by biergaizi** [comment]
Never mix stable or unstable keywords.

**Comment by PeterCxy** [comment]
@biergaizi okay, I'll remove the amd64 tomorrow

**Comment by PeterCxy** [comment]
oh I should remove the ~x86

**Comment by PeterCxy** [comment]
@biergaizi fixed.

**Pull request merged**
