### PR TITLE
WineQQ from Deepin

### PR DESCRIPTION
**Pull request by zhtengw**
At present, wineQQ packaged by deepin is the best and newest version of Tencent QQ for linux. I write a ebuild to merge it into Gentoo. But I need some helps. 
After merge into system, the deepin-wineqq can only run in Deepin Desktop Evironment. And I got errors in other DEs (I only tested in KDE and LXQt):
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  10
  Current serial number in output stream:  10
```
Can any one help me?

PS1: Deepin Team says that there is no restriction for merging deepin-wine packages to other Linux Distributions.

PS2: sreenshot for deepin-wineQQ running in Gentoo DDE

### CODE REVIEW

**Comment by tolbkni** [comment]
@zhtengw Can you try to run this command `xprop -root` under different DEs, and paste output results here?

ref: https://bugzilla.redhat.com/show_bug.cgi?id=869959

**Comment by zhtengw** [comment]
Thanks @tolbkni. 
Here are output results:
[xprop_par_DDE.txt](https://github.com/microcai/gentoo-zh/files/820659/xprop_par_DDE.txt)
[xprop_par_KDE.txt](https://github.com/microcai/gentoo-zh/files/820658/xprop_par_KDE.txt)
[xprop_par_LxQt.txt](https://github.com/microcai/gentoo-zh/files/820660/xprop_par_LxQt.txt)

**Comment by zhtengw** [comment]
I installed DeepinOS to test, and have confirmed that it is an upstream issue. But deepin-wine in other DE would not get technical support from Deepin Team. So, the deepi-wine QQ can only run in DDE now. See [this thread](https://bbs.deepin.org/forum.php?mod=viewthread&tid=135663) for details.

**Comment by vizv** [comment]
@zhtengw I tried your ebuild today, but version `8.1.17255deepin9` is outdated, `8.9.19983deepin16` is the latest version. I'm generating Manifest right now, and I'll let you know once I finished emerging.

**Comment by zhtengw** [comment]
@vizv I have submitted new commints to bump new deepin-wine-QQ.

**Comment by vizv** [comment]
@zhtengw Just curious did you put `deepin-wine-QQ` and `deepin-wine-wechat` in the wrong directory?

Do you really mean to put `deepin-wine-*` in `net-im/net-im`?
Also for `app-emulation/app-emulation/deepin-wine`?

**Comment by zhtengw** [comment]
My mistake! Thank you @vizv .

**Comment by vizv** [comment]
It probably takes me whole night to download these deb files, I'll tell you how they work tomorrow. n8t.

**Comment by vizv** [comment]
@zhtengw I finished emerging, but I got the following error:

```
wine: failed to initialize: libudis86.so.0: cannot open shared object file: No such file or directory
```

It seemed `deepin-wine` might need some shared 32-bit libraries, so I turned on `abi_x86_32` for `dev-libs/udis86` and ran again but got the following segfault this time:

```
/usr/bin/deepin-wine: line 45: 30592 Segmentation fault      WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"
```


I think there might be some dependencies of `wine` I didn't emerge, so I'm emerging `=app-emulation/wine-2.3` and will tell you if this helps to fix the segfault.

**Comment by zhtengw** [comment]
@vizv Actually I missed the abi_x86_32 USE flag for all the depended packages. My mistake again.

**Comment by vizv** [comment]
@zhtengw no worry, you are doing a great job. I'm testing the new ebuild for `app-emulation/deepin-wine` and I'll let you know the result asap.

**Comment by vizv** [comment]
I'm still getting the segfault... I didn't use `systemd`, could this be the problem?

```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_CA.utf8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (306A9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 76804088 bytes (74 MiB)

Extracting archive: /opt/deepinwine/apps/Deepin-QQ/files.7z
--
Path = /opt/deepinwine/apps/Deepin-QQ/files.7z
Type = 7z
Physical Size = 76804088
Headers Size = 17144
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Folders: 292
Files: 1510
Size:       257682709
Compressed: 76804088
Traceback (most recent call last):
  File "/opt/deepinwine/tools/add_hotkeys", line 42, in <module>
    add_qq_shortcut(u"提取QQ消息", " z", "<Control><Alt>Z")
  File "/opt/deepinwine/tools/add_hotkeys", line 29, in add_qq_shortcut
    keybinding = bus.get_object("com.deepin.daemon.Keybinding", "/com/deepin/daemon/Keybinding")
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.daemon.Keybinding was not provided by any .service files
/usr/bin/deepin-wine: line 45: 14207 Segmentation fault      WINEPREFIX=$wineprefix WINELOADER=$wineloader WINEDEBUG=$winedebug $wine "$@"
```

**Comment by zhtengw** [comment]
@vizv, I can not reproduce this ```Segmentation fault```.
Although I'm using ```systemd```, but I don't think your issue is related to systemd. The error message you saw is just means that you need dde-daemon to enable keybinding for deepin-wine-QQ.
I unmerged dde-daemon and launch LXQt, what I got is:
```
/opt/deepinwine/apps/Deepin-QQ/run.sh

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (306A9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 76804088 bytes (74 MiB)          

Extracting archive: /opt/deepinwine/apps/Deepin-QQ/files.7z
--
Path = /opt/deepinwine/apps/Deepin-QQ/files.7z
Type = 7z
Physical Size = 76804088
Headers Size = 17144
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok                                                             

Folders: 292
Files: 1510
Size:       257682709
Compressed: 76804088
Traceback (most recent call last):
  File "/opt/deepinwine/tools/add_hotkeys", line 42, in <module>
    add_qq_shortcut(u"提取QQ消息", " z", "<Control><Alt>Z")
  File "/opt/deepinwine/tools/add_hotkeys", line 29, in add_qq_shortcut
    keybinding = bus.get_object("com.deepin.daemon.Keybinding", "/com/deepin/daemon/Keybinding")
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib64/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib64/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.daemon.Keybinding was not provided by any .service files

 X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  10
```

**Comment by vizv** [comment]
It might be a dependency issue, I patch the ebuild a little bit according to the deb control. Let's see if this helps.

```diff
--- /tmp/gentoo-zh-9fac5763e91b55104bb8b009a8bfe20d2385c2c8/app-emulation/deepin-wine/deepin-wine-1.9.24-r1.ebuild	2017-04-13 23:22:11.000000000 -0300
+++ /usr/local/portage/local/app-emulation/deepin-wine/deepin-wine-1.9.24-r1.ebuild	2017-04-14 11:31:14.382844205 -0300
@@ -33,8 +33,15 @@
 	media-sound/pulseaudio[abi_x86_32]
 	media-libs/glu[abi_x86_32]
 	media-libs/mesa[abi_x86_32]
+	virtual/libudev[abi_x86_32]
+	virtual/opencl[abi_x86_32]
+	dev-libs/libusb[abi_x86_32]
+	x11-libs/libX11[abi_x86_32]
+	x11-libs/libXext[abi_x86_32]
+	dev-libs/libxml2[abi_x86_32]
 	dev-libs/udis86[abi_x86_32]
-	sys-libs/zlib[abi_x86_32]"
+	sys-libs/zlib[abi_x86_32]
+	x11-libs/libXcursor[abi_x86_32]"
 
 S=${WORKDIR}
```

**Comment by microcai** [comment]
any update on this ?

**Comment by vizv** [comment]
@microcai I tried on my laptop, without DeepinDesktop I can't get WineQQ to work.

**Pull request merged**
