### PR TITLE
shadowsocks-qt5 && libQtShadowsocks

### PR DESCRIPTION
**Pull request by aieu**
- mv net-proxy/libQtShadowsocks to dev-qt/libQtShadowsocks
- dev-qt/libQtShadowsocks: version bump to 1.9.0
- net-proxy/shadowsocks-qt5: version bump to 2.7.0

### CODE REVIEW

**Comment by OwenChia** [comment]
升级报错，文件冲突。
是不是最好暂时先保留下 net-proxy 里的？

```
 * Messages for package dev-qt/libQtShadowsocks-1.9.0:

 * This package will overwrite one or more files that may belong to other
 * packages (see list below). You can use a command such as `portageq
 * owners / <filename>` to identify the installed package that owns a
 * file. If portageq reports that only one package owns a file then do
 * NOT file a bug report. A bug report is only useful if it identifies at
 * least two or more packages that are known to install the same file(s).
 * If a collision occurs and you can not explain where the file came from
 * then you should simply ignore the collision since there is not enough
 * information to determine if a real problem exists. Please do NOT file
 * a bug report at http://bugs.gentoo.org unless you report exactly which
 * two packages install the same file(s). See
 * http://wiki.gentoo.org/wiki/Knowledge_Base:Blockers for tips on how to
 * solve the problem. And once again, please do NOT file a bug report
 * unless you have completely understood the above message.
 *
 * Detected file collision(s):
 *
 *      /usr/lib/pkgconfig/QtShadowsocks.pc
 *      /usr/include/qtshadowsocks/addresstester.h
 *      /usr/include/qtshadowsocks/QtShadowsocks
 *      /usr/include/qtshadowsocks/address.h
 *      /usr/include/qtshadowsocks/socketstream.h
 *      /usr/include/qtshadowsocks/export.h
 *      /usr/include/qtshadowsocks/tcpserver.h
 *      /usr/include/qtshadowsocks/controller.h
 *      /usr/include/qtshadowsocks/rc4.h
 *      /usr/include/qtshadowsocks/common.h
 *      /usr/include/qtshadowsocks/tcprelay.h
 *      /usr/include/qtshadowsocks/encryptor.h
 *      /usr/include/qtshadowsocks/chacha.h
 *      /usr/include/qtshadowsocks/profile.h
 *      /usr/include/qtshadowsocks/httpproxy.h
 *      /usr/include/qtshadowsocks/udprelay.h
 *      /usr/include/qtshadowsocks/encryptorprivate.h
 *      /usr/include/qtshadowsocks/cipher.h
 *      /usr/lib/libQtShadowsocks.so
 *      /usr/lib/libQtShadowsocks.so.1
 *
 * Searching all installed packages for file collisions...
 *
 * Press Ctrl-C to Stop
 *
 * dev-qt/libQtShadowsocks-1.8.4:0::gentoo-zh
 *      /usr/include/qtshadowsocks/QtShadowsocks
 *      /usr/include/qtshadowsocks/address.h
 *      /usr/include/qtshadowsocks/addresstester.h
 *      /usr/include/qtshadowsocks/chacha.h
 *      /usr/include/qtshadowsocks/cipher.h
 *      /usr/include/qtshadowsocks/common.h
 *      /usr/include/qtshadowsocks/controller.h
 *      /usr/include/qtshadowsocks/encryptor.h
 *      /usr/include/qtshadowsocks/encryptorprivate.h
 *      /usr/include/qtshadowsocks/export.h
 *      /usr/include/qtshadowsocks/httpproxy.h
 *      /usr/include/qtshadowsocks/profile.h
 *      /usr/include/qtshadowsocks/rc4.h
 *      /usr/include/qtshadowsocks/socketstream.h
 *      /usr/include/qtshadowsocks/tcprelay.h
 *      /usr/include/qtshadowsocks/tcpserver.h
 *      /usr/include/qtshadowsocks/udprelay.h
 *      /usr/lib/libQtShadowsocks.so
 *      /usr/lib/libQtShadowsocks.so.1
 *      /usr/lib/pkgconfig/QtShadowsocks.pc
 *
 * Package 'dev-qt/libQtShadowsocks-1.9.0' NOT merged due to file
 * collisions. If necessary, refer to your elog messages for the whole
 * content of the above message.
```

**Comment by aieu** [comment]
主要是用 qt5-build.eclass 比较方便，剥离一个libqss用use flag来按需编译

关于冲突，是我没注意了，不过
1. Issue `git mv net-misc/fwbuilder net-firewall/fwbuilder`
2. Add the following entry to the latest file in profile/updates/: `move net-misc/fwbuilder` net-firewall/fwbuilder
3. Update the reverse dependencies of the package
4. Update profiles/package.mask and other related files under profiles/
5. Check the eclasses that may be referencing the package
6. Update all the metadata.xml files which contain a reference to this package using the <pkg> tag or the restrict attribute.
   8.Stage all the changed files using git add. For example: git add profiles/package.mask
7. Commit all the changes in one commit using: git commit --gpg-sign
8. Update any news items referencing the package in a Display-If-Installed header or in the item's body (and increment their Revision).
9. Update any open bugs related to the package

我应该没做错吧...

**Comment by aieu** [comment]
刚刚过去把  <net-proxy/libQtShadowsocks-1.9.0 maks了
你现在看看呢

**Comment by OwenChia** [comment]
呃，已经卸掉 libQtShadowsocks 重装了……

**Pull request merged**
