### PR TITLE
x11-misc/fqterm: add dependency to fix build fails

### LINKED ISSUE #1430: x11-misc/fqterm-0.9.10.1 fails to compile
https://bugs.gentoo.org/826318

### PR DESCRIPTION
**Pull request by OriPoin**
https://bugs.gentoo.org/826318

close https://github.com/microcai/gentoo-zh/issues/1430

fix https://github.com/microcai/gentoo-zh/issues/1430

Signed-off-by: OriPoin <OriPoin@outlook.com>

### CODE REVIEW

**Comment by OriPoin** [comment]
请先不要合并，有QA问题，稍后force push

**Comment by liangyongxiang** [comment]
@OriPoin 可以手动转成draft

**Comment by OriPoin** [comment]
现在可以了

**Comment by aieu** [comment]
fix close 选一个即可
其他类似的关键词还有其他
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Pull request merged**
