### PR TITLE
net-proxy/v2ray-bin:bump to 4.20.0

### PR DESCRIPTION
**Pull request by rfuy**
版本太旧了，升级到最新版并重写了initd

### CODE REVIEW

**Comment by microcai** [comment]
it'll be even better to have non-bin package

**Comment by ofree** [comment]
In my opition, just removing '-bin' is wrong, it's actually a binary
release version

We should reserve the non '-bin' package for real go source build package

microcai <notifications@github.com> 于 2019年9月17日周二 上午12:57写道：

**Comment by microcai** [comment]
@ofree no  -bin suffix is acceptable if that's the only package.

**Comment by ofree** [comment]
I'll try to explore the possibility to have a source build version, but no
promises

So, I guess a pkg moving is acceptable for you when that happens

microcai <notifications@github.com> 于 2020年3月29日周日 下午4:34写道：

**Pull request merged**
