### PR TITLE
dev-cpp/tgbot-cpp: bump version

### LINKED ISSUE #1840: [nvchecker] dev-cpp/tgbot-cpp can be bump to 1.3
oldver: 1.3_p211229

### LINKED ISSUE #2109: [nvchecker] dev-cpp/tgbot-cpp can be bump to 1.3
oldver: 1.3_p211229
CC: @CHN-beta

### PR DESCRIPTION
**Pull request by Linerre**
fix https://github.com/microcai/gentoo-zh/issues/2109
fix https://github.com/microcai/gentoo-zh/issues/1840

### CODE REVIEW

**Comment by Linerre** [comment]
@CHN-beta 你看这样合适吗？

nvchecker 认为 1.3 比 1.3_pxxxxxx 新，但是按照 Gentoo Dev Manual[^1]，后者 patch release 更新一些:
>There can be a suffix to version indicating the kind of release. In the following table, what Portage considers to be the 'lowest' version comes first. 

我只是把 patch release 从 https://github.com/reo7sp/tgbot-cpp/commit/406d8e4d87232491bc14fcbee4689378f6bf9414 更新到了 https://github.com/reo7sp/tgbot-cpp/commit/5567c5cfc88b2111221dbfca99919fe3fe17eb8a

[^1]:https://devmanual.gentoo.org/ebuild-writing/file-format/index.html#file-naming-rules

**Comment by CHN-beta** [comment]
> @CHN-beta 你看这样合适吗？
> 
> nvchecker 认为 1.3 比 1.3_pxxxxxx 新，但是按照 Gentoo Dev Manual[^1]，后者 patch release 更新一些:
> >There can be a suffix to version indicating the kind of release. In the following table, what Portage considers to be the 'lowest' version comes first. 
> 
> 我只是把 patch release 从 https://github.com/reo7sp/tgbot-cpp/commit/406d8e4d87232491bc14fcbee4689378f6bf9414 更新到了 https://github.com/reo7sp/tgbot-cpp/commit/5567c5cfc88b2111221dbfca99919fe3fe17eb8a
> 
> [^1]:https://devmanual.gentoo.org/ebuild-writing/file-format/index.html#file-naming-rules

合适啊，没什么不合适的。

**Comment by liangyongxiang** [comment]
> 合适啊，没什么不合适的。


如果你觉得没有问题，你可以approve

**Review by CHN-beta — APPROVED** [review]
good

**Pull request merged**
